namespace Level
{
    public enum PropKind
    {
        None = 0,
        Battery = 1,
        BeerBottle = 2,
        Binoculars = 3,
        Book = 4,
        PlasticBottle = 5,
        BulletShell = 6,
        CafeChair = 7,
        Camera = 8,
        TinCan = 9,
        ChampagneBottle = 10,
        Chemical = 11,
        Compass = 12,
        Container = 13,
        Drill = 14,
        Fan = 15,
        Flashlight = 16,
        FlowerPot = 17,
        Gramophone = 18,
        Lamp = 19,
        Laptop = 20,
        Matchbox = 21,
        Phone = 22,
        Radio = 23,
        CerealBox = 24,
        Television = 25,
        WalkieTalkie = 26,
        WireCutters = 27,
        Cup = 28,
    }
}